default_platform(:ios)

platform :ios do
  lane :build_app_lane do
    
    team_id = ENV["IOS_TEAM_ID"]
    bundle_id = ENV["BUNDLE_ID"]
    profile_name = ENV["IOS_PROFILE_NAME"]

    build_app(
      workspace: "ios/App/App.xcworkspace",
      scheme: "App",
      configuration: "Release",
      export_method: "app-store",
      # Takım kimliğini ve imzalama gerekliliklerini buraya zorla ekliyoruz
      export_xcargs: "-allowProvisioningUpdates DEVELOPMENT_TEAM=#{team_id}",
      export_options: {
        method: "app-store",
        teamID: team_id,
        provisioningProfiles: {
          bundle_id => profile_name
        }
      }
    )
  end
end
