default_platform(:ios)

platform :ios do
  desc "Uygulamayi derle ve IPA cikart"
  lane :build_app_lane do
    
    # GitHub Secrets'tan gelen değişkenleri tanımlıyoruz
    team_id = ENV["IOS_TEAM_ID"]
    bundle_id = ENV["BUNDLE_ID"]
    profile_name = ENV["IOS_PROFILE_NAME"]

    # Otomatik imzalama hatalarını engellemek için doğrudan export_options kullanıyoruz
    build_app(
      workspace: "ios/App/App.xcworkspace",
      scheme: "App",
      configuration: "Release",
      export_method: "app-store",
      export_options: {
        method: "app-store",
        teamID: team_id,
        provisioningProfiles: {
          bundle_id => profile_name
        },
        compile_bitcode: false
      }
    )
  end
end
